<a href="https://colab.research.google.com/github/Bilalafzal02/Python_Projects/blob/main/NumpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr_n1 = np.array([1,2,3,4,5])
print("Array:", arr_n1)
print("Type: ", arr_n1.dtype)
print()

Array: [1 2 3 4 5]
Type:  int64



In [3]:
# Use np.arange() to create a 1D array of numbers from 10 to 50.
# shapr and size
import numpy as np
arr_n1 = np.arange(10, 51)
print("shape: ", arr_n1.shape)
print("size: ", arr_n1.size)
print()


shape:  (41,)
size:  41



In [9]:
#Create a 2D NumPy array of shape (3, 4) filled with zeros using np.zeros().
# Convert all zeros into fives.
import numpy as np

zero = np.zeros ((3,4))
print("Zeros: \n", zero)
full = np.full((3,4),5)
print("Full Seven: \n",full)
print()

Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Full Seven: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]



In [20]:
#Generate a 1D array of 15 random integers between 1 and 100 using np.random.randint().
# Find the maximum, minimum, and mean values.

import numpy as np
arr_1d = np.random.randint(1,100)
print("arr",arr_1d)

arr_1d = np.random.randint(1,100,15)
print("arr",arr_1d)
sort =np.sort(arr_1d)
print("sort",sort)
max = np.max(arr_1d)
print("max",max)
min = np.min(arr_1d)
print("min",min)
mean = np.mean(arr_1d)
print("mean",mean)
print()


arr 91
arr [13 96 74 56 70 83 48 34 76 54 36 91 26 27 99]
sort [13 26 27 34 36 48 54 56 70 74 76 83 91 96 99]
max 99
min 13
mean 58.86666666666667



In [34]:
# Create a NumPy array [10, 20, 30, 40, 50]
import numpy as np

arr = np.array([10,20,30,40,50])
print("First element: ", arr[0])
print("Last element: ", arr[-1])
print()


First element:  10
Last element:  50



In [5]:
#Create a NumPy array of numbers from 1 to 20.
# Extract only the even numbers using slicing or boolean indexing.
# Reverse the array using slicing.
import numpy as np
arr = np.arange(1,21)
print(arr)
even = arr[arr%2 ==0]
print("even: ",even)
reverse = arr[::-1]
print("reverse: ",reverse)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
even:  [ 2  4  6  8 10 12 14 16 18 20]
reverse:  [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]



In [7]:
# Make a 2D array of shape (4, 4) with numbers from 1 to 16.
import numpy as np

arr_2d = np.arange(1,17).reshape(4,4)
print(arr_2d)
print("first two rows: ",arr_2d[:2, -2:])
#print("Last two coloms: ",arr_2d[ 1:,-2])
print()
np.fill_diagonal(arr_2d,0)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
first two rows:  [[3 4]
 [7 8]]

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [7]:
# Create an array of 25 random integers between 1 and 100.
#Sort the array using np.sort().
import numpy as np

arr = np.random.randint(1,101,25)
print(arr)
arry1=np.sort(arr)
print(arry1)

[51 71 15 55 23 29 29 30 44 90 95 62 96 96 72 42 30 41 39 54  5 75 29 67
 43]
[ 5 15 23 29 29 29 30 30 39 41 42 43 44 51 54 55 62 67 71 72 75 90 95 96
 96]


In [12]:
# Create a 1D array of numbers from 1 to 10 and find:
# Maximum (np.max())
# Minimum (np.min())
# Sum (np.sum())
import numpy as np

arr_1d = np.arange(1,11)
print(arr_1d)
max = arr_1d.max()
print("max: ",max)
mini = arr_1d.min()
print("Mini",mini)
sum = arr_1d.sum()
print("sum",sum)

[ 1  2  3  4  5  6  7  8  9 10]
max:  10
Mini 1
sum 55


In [20]:
# Reshape a 1D array of 36 elements into a 2D array of shape (6, 6).
# Find the sum of each row and each column using np.sum() with axis.

import numpy as np

arr_1d = np.arange(1,37)
print(arr_1d)
arr_2d = arr_1d.reshape(6,6)
print(arr_2d)
sum = np.sum(arr_2d,axis=1)
sum1=np.sum(arr_2d,axis=0)
print("row_sum",sum)
print("sum_colm",sum1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
row_sum [ 21  57  93 129 165 201]
sum_colm [ 96 102 108 114 120 126]
